services:

  db:
    image: mariadb
    restart: always
    volumes:
      - database:/var/lib/mysql
#      - ./database:/docker-entrypoint-initdb.d
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: mydb
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  database:
