-- MySQL Script generated by MySQL Workbench
-- Mon Feb 24 16:21:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `nameDiscriminator` DECIMAL(4) NOT NULL,
  `passwordHash` VARCHAR(45) NOT NULL,
  `passwordSalt` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FriendRequset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FriendRequset` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FriendRequset` (
  `User_idUser` INT NOT NULL,
  `Recipient` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `Recipient`),
  CONSTRAINT `fk_FriendRequset_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Friend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Friend` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Friend` (
  `User_idUser` INT NOT NULL,
  `User_idUser1` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `User_idUser1`),
  INDEX `fk_User_has_User_User2_idx` (`User_idUser1` ASC) VISIBLE,
  INDEX `fk_User_has_User_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_User_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_User_User2`
    FOREIGN KEY (`User_idUser1`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `idCourse` INT NOT NULL,
  `CourseName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCourse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Module` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Module` (
  `idModule` INT NOT NULL,
  `ModuleName` VARCHAR(45) NOT NULL,
  `Course_idCourse` INT NOT NULL,
  PRIMARY KEY (`idModule`),
  INDEX `fk_Module_Course1_idx` (`Course_idCourse` ASC) VISIBLE,
  CONSTRAINT `fk_Module_Course1`
    FOREIGN KEY (`Course_idCourse`)
    REFERENCES `mydb`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mission` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mission` (
  `idMission` INT NOT NULL,
  `maxPoints` INT NOT NULL,
  `Module_idModule1` INT NOT NULL,
  `MissionName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMission`),
  INDEX `fk_Mission_Module1_idx` (`Module_idModule1` ASC) VISIBLE,
  CONSTRAINT `fk_Mission_Module1`
    FOREIGN KEY (`Module_idModule1`)
    REFERENCES `mydb`.`Module` (`idModule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Group` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Group` (
  `idGroup` INT NOT NULL,
  `GroupOwner` INT NOT NULL,
  `GroupName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGroup`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GroupMember`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GroupMember` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GroupMember` (
  `Group_idGroup` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`Group_idGroup`, `User_idUser`),
  INDEX `fk_Group_has_User_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_Group_has_User_Group1_idx` (`Group_idGroup` ASC) VISIBLE,
  CONSTRAINT `fk_Group_has_User_Group1`
    FOREIGN KEY (`Group_idGroup`)
    REFERENCES `mydb`.`Group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Group_has_User_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MissionCompleted`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MissionCompleted` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MissionCompleted` (
  `Mission_idMission` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `Points` INT NULL,
  `CompletionTime` DATE NULL,
  `StartTime` DATE NULL,
  PRIMARY KEY (`Mission_idMission`, `User_idUser`),
  INDEX `fk_Mission_has_User_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_Mission_has_User_Mission1_idx` (`Mission_idMission` ASC) VISIBLE,
  CONSTRAINT `fk_Mission_has_User_Mission1`
    FOREIGN KEY (`Mission_idMission`)
    REFERENCES `mydb`.`Mission` (`idMission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mission_has_User_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Achievement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Achievement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Achievement` (
  `idAchievement` INT NOT NULL,
  `AchievementName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAchievement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_Achievement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User_has_Achievement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User_has_Achievement` (
  `User_idUser` INT NOT NULL,
  `Achievement_idAchievement` INT NOT NULL,
  `Time` DATE NULL,
  PRIMARY KEY (`User_idUser`, `Achievement_idAchievement`),
  INDEX `fk_User_has_Achievement_Achievement1_idx` (`Achievement_idAchievement` ASC) VISIBLE,
  INDEX `fk_User_has_Achievement_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Achievement_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Achievement_Achievement1`
    FOREIGN KEY (`Achievement_idAchievement`)
    REFERENCES `mydb`.`Achievement` (`idAchievement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
