# Generated by Django 5.2.1 on 2025-05-16 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingCourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='border',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='programmingCourse.item'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='programmingCourse.item'),
        ),
    ]
