# Generated by Django 5.1.7 on 2025-04-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingCourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gatcha',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
