# Generated by Django 5.2.1 on 2025-05-17 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingCourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmingCourse.course'),
        ),
    ]
