# Generated by Django 5.2.1 on 2025-05-18 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingCourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='border',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='programmingCourse.item'),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmingCourse.course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='programmingCourse.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemType',
            field=models.CharField(choices=[('collectible', 'collectible'), ('other', 'other'), ('theme', 'theme'), ('title', 'title'), ('border', 'border')], max_length=1000),
        ),
    ]
