# Generated by Django 5.1.7 on 2025-03-27 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingCourse', '0002_group_description_group_image_group_is_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
