# Generated by Django 5.1.6 on 2025-03-12 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingCourse', '0002_alter_groupmessage_user_alter_friend_user1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.UniqueConstraint(fields=('name', 'module'), name='unique_Mission'),
        ),
        migrations.AddConstraint(
            model_name='missioncompleted',
            constraint=models.UniqueConstraint(fields=('name', 'module'), name='unique_Mission_complete'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('name', 'course'), name='unique_module'),
        ),
    ]
