# Generated by Django 5.1.6 on 2025-03-12 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingCourse', '0003_mission_unique_mission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='missioncompleted',
            name='unique_Mission_complete',
        ),
        migrations.AddConstraint(
            model_name='missioncompleted',
            constraint=models.UniqueConstraint(fields=('user', 'mission'), name='unique_Mission_complete'),
        ),
    ]
