# Generated by Django 5.1.6 on 2025-03-12 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingCourse', '0004_remove_missioncompleted_unique_mission_complete_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='missioncompleted',
            name='unique_Mission_complete',
        ),
        migrations.AddConstraint(
            model_name='missioncompleted',
            constraint=models.UniqueConstraint(fields=('user', 'mission'), name='unique_complete'),
        ),
    ]
