# Generated by Django 5.1.6 on 2025-03-12 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingCourse', '0007_course_id_alter_course_name_course_unique_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programmingCourse.course'),
            preserve_default=False,
        ),
    ]
