# Generated by Django 5.1.6 on 2025-03-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingCourse', '0009_remove_mission_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='missioncompleted',
            name='answer',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
